### ISSUE TITLE
Utiliser Transifex ?

### ISSUE THREAD

**Issue by glonlas** [Tyr62/Shadowrun-Dragonfall#1]
Salut,

Merci pour l'initiative, c'est une très bonne idée.
Pour les traductions sais-tu que tu pourrais utiliser gratuitement Transifex http://www.transifex.com/ ?
Nous pourrions collaborer et proposer des traductions à plusieurs sans devoir te faire des modif dans un fichier Excel.

**Comment by Tyr62** [comment]
Bonjour glonlas,

Sauf erreur de ma part, Transifex n'est pas gratuit; au mieux, tu as une période de test de 30 jours, ou alors j'ai loupé quelque chose au niveau du plan tarifaire.

**Comment by glonlas** [comment]
Bonjour,

Pour un projet Opensource et ouvert c'est totalement gratuit (mais ils le cachent bien, je l'ai mis en place pour un projet Opensource https://www.transifex.com/projects/p/agilestoryprint/).
Tu vas pouvoir t'inscrire ici : https://www.transifex.com/signup/

Tu pourras même demander à Transifex de se synchroniser avec ce repot Github.
Je peux t'aider si tu as besoin.

Très bonne journée,

Gerald

**Comment by Tyr62** [comment]
Je vais jeter un oeil
